apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: devops
  labels:
    app.kubernetes.io/name: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: devops-retained-storage
  volumeName: nexus-pv
  resources:
    requests:
      storage: 20Gi
