apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
  namespace: devops
  labels:
    app.kubernetes.io/name: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: devops-retained-storage
  volumeName: sonarqube-pv
  resources:
    requests:
      storage: 10Gi
