apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devops
  labels:
    app.kubernetes.io/name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: devops-retained-storage
  volumeName: postgres-pv
  resources:
    requests:
      storage: 5Gi
